
#' Segmentation class
#'
#' S4 class holding all the data necessary for plotting specific slices, maximum projection of structures, and plotting data from assays
#'
#' @slot slices A nested list containing `segPointSet` items for the 3 axes ("sagittal", "coronal", "axial")
#' @slot ontology A `data.frame` containing the structural ontology
#' @slot outlines A list of `data.frame`s containing coordinates for the total outline for each axis
#' @slot metadata A list of metadata generated by `seg_draw()`
#' @slot structure_tables A list of tables with structure per slice per plane generated by `seg_draw()`
#' @slot assays A list of objects of class \code{segmentationAssay} containing assay data
#' @slot projections A list of maximum projections
#' @slot meshes A list of \code{mesh3d} objects, named according to structure acronyms

setClass("segmentation", representation(
  slices = "list",
  ontology = "data.frame",
  outlines = "list",
  metadata = "list",
  structure_tables = "list",
  assays = "list",
  projections = "list",
  meshes = "list"
))

#' Segmentation point set class
#'
#' S4 class holding all the data necessary to build a set of polygons via `poly_build()` in order to be plotted.
#'
#' @slot coords A `data.frame` containing ordered `x` and `y` coordinates for polygon drawing
#' @slot slice A `character` containing the slice number
#' @slot structure A `character` containing the structure ID
#' @slot id A `character` containing the polygon ID (group level aesthetic for plotting)
#' @slot subid A `character` containing the polygon sub-ID (subgroup level aesthetic for plotting)

setClass("segPointSet", representation(
  coords = "data.frame",
  slice = "character",
  structure = "character",
  id = "character",
  subid = "character"
))

#' segmentationAssay class
#'
#' S4 class holding numerical values for features in samples, and a one-to-many mapping for every sample to one or more structures
#'
#' @slot values A `matrix` containing features (rows) in each sample (columns)
#' @slot mapping A `list` in which each sample (list item name) contains the segmentation structural IDs to which samples are mapped
#' @slot sampledata A `data.frame` containing other information on samples (e.g. description, sample metadata)

setClass("segmentationAssay", representation(
  values = "matrix",
  mapping = "list",
  sampledata = "data.frame"
))


#' Metadata getter (generic)
#'
#' S4 method to access the \code{metadata} slot in \code{segmentation} class objects
#' @param x a \code{segmentation} class object

setGeneric("seg_metadata", function(x) {
  standardGeneric("seg_metadata")
})

#' Metadata getter (method)
#'
#' S4 method to access the \code{metadata} slot in \code{segmentation} class objects
#' @param x a \code{segmentation} class object

setMethod("seg_metadata", c(x = "segmentation"), function(x) {
  return(x@metadata)
})

#' Metadata setter (generic)
#'
#' S4 method to set the \code{metadata} slot in \code{segmentation} class objects
#' @param x a \code{segmentation} class object
#' @param value a list containing segmentation metadata

setGeneric("seg_metadata<-", function(x, value) {
  standardGeneric("seg_metadata<-")
})

#' Metadata setter (method)
#'
#' S4 method to set the \code{metadata} slot in \code{segmentation} class objects
#' @param x a \code{segmentation} class object
#' @param value a list containing segmentation metadata

setMethod("seg_metadata<-", c(x = "segmentation"), function(x, value) {
  x@metadata <- value
  x
})

#' Ontology getter (generic)
#'
#' S4 method to get the \code{ontology} slot in \code{segmentation} class objects
#' @param x a \code{segmentation} class object

setGeneric("ontology", function(x) {
  standardGeneric("ontology")
})

#' Ontology setter (generic)
#'
#' S4 method to set the \code{ontology} slot in \code{segmentation} class objects
#' @param x a \code{segmentation} class object
#' @param value a table containing the ontology tree

setGeneric("ontology<-", function(x, value) {
  standardGeneric("ontology<-")
})

#' Ontology getter (method)
#'
#' S4 method to get the \code{ontology} slot in \code{segmentation} class objects
#' @param x a \code{segmentation} class object

setMethod("ontology", c(x = "segmentation"), function(x) {
  return(x@ontology)
})

#' Ontology setter (method)
#'
#' S4 method to set the \code{ontology} slot in \code{segmentation} class objects, with sanity checks.
#' @param x a \code{segmentation} class object
#' @param value a table containing the ontology tree

setMethod("ontology<-", c(x = "segmentation"), function(x, value) {
  if(is.null(value)) stop("Segmentation objects must have an ontology")
  if(class(value) != "data.frame") stop("The ontology must be of class `data.frame`")
  missing_fields <- setdiff(c("id", "name", "acronym", "parent_structure_id", "structure_id_path", "col"), colnames(value))
  if(length(missing_fields) > 0) stop(paste0("Columns ", paste(missing_fields, collapse = ", ")), " were not found in the ontology. \n Please provide a complete ontology table.")
  x@ontology <- value
  x
})

#' Assay getter (generic)
#'
#' S4 method to get the \code{assays} slot in \code{segmentation} class objects
#' @param x a \code{segmentation} class object

setGeneric("assays", function(x) {
  standardGeneric("assays")
})

#' Assay getter (method)
#'
#' S4 method to get the \code{assays} slot in \code{segmentation} class objects
#' @param x a \code{segmentation} class object

setMethod("assays", c(x = "segmentation"), function(x) {
  return(x@assays)
})

#' Projection getter (generic)
#'
#' S4 method to get the \code{projections} slot in \code{segmentation} class objects
#' @param x a \code{segmentation} class object
#' @param name character, the name of the projection

setGeneric("projections", function(x, name) {
  standardGeneric("projections")
})

#' Projection getter (method)
#'
#' S4 method to get the \code{projections} slot in \code{segmentation} class objects
#' @param x a \code{segmentation} class object
#' @param name character, the name of the projection

setMethod("projections", c(x = "segmentation"), function(x, name) {
  return(x@projections[[name]])
})

#' Show segmentation
#'
#' S4 method to show the preview of a \code{segmentation} class objects
#' @param object a \code{segmentation} class object

setMethod("show", "segmentation", function(object) {
  if(seg_metadata(object)$units == "Unknown") units <- "Unknown" else units <- c("Unknown", "m", "mm", "micron")[seg_metadata(object)$units + 1]
  cat("      Segmentation from file: ", seg_metadata(object)$filename, "\n")
  cat("                    Plane(s): ", paste(seg_metadata(object)$planes, collapse = ", "), "\n")
  cat("                  Directions: ", paste(seg_metadata(object)$dirs, collapse = " to "), "\n")
  cat("       Dimensions (original): ", paste(seg_metadata(object)$dims_original, collapse = " x "), "\n")
  cat("      Dimensions (effective): ", paste(seg_metadata(object)$dims_effective, collapse = " x "), "\n")
  cat("            Pixel dimensions: ", paste(seg_metadata(object)$pixdim, collapse = " x "), "\n")
  cat("             Dimension units: ", units, "\n")
  cat("             Reference space: ", seg_metadata(object)$reference_space, "\n")
  cat("              Structures (n): ", length(seg_metadata(object)$structures), "\n")
  cat("             Structures (ID): ", paste(head(seg_metadata(object)$structures), collapse = ", "), "and", (length(seg_metadata(object)$structures) - length(head(seg_metadata(object)$structures))), "more. \n")
  cat("       Structures (acronyms): ", paste(head(ontology(object)[as.character(seg_metadata(object)$structures), "acronym"]), collapse = ", "), "and", (length(ontology(object)[seg_metadata(object)$structures, "acronym"]) - length(head(ontology(object)[seg_metadata(object)$structures, "acronym"]))), "more. \n")
  cat("Type citation(\"name_of_segmentation\") to display the citation(s) for this segmentation.", sep = "")
  })


#' Show citation (generic)
#'
#' S4 method to show the \code{citation} slot of a \code{segmentation} class objects
#' @param x a \code{segmentation} class object

setGeneric("citation", function(x) {
  standardGeneric("citation")
})

#' Show citation (method)
#'
#' S4 method to show the \code{citation} slot of a \code{segmentation} class objects
#' @param x a \code{segmentation} class object

setMethod("citation", "segmentation", function(x) {
  for(n in names(seg_metadata(x)$citation)) {
    cat("Citation (", n, "):\n", sep = "")
    cat(seg_metadata(x)$citation[[n]], "\n\n")
    }
})


