
#' S4 class representing a segmentation.
#'
#' Holds all the data necessary for plotting specific slices, maximum projection of structures, recreate the original array.
#'
#' @slot slices A list containing `segPointSet` instances for the 3 axes ("sagittal", "coronal", "axial")
#' @slot ontology A `data.frame` containing the structural ontology
#' @slot outlines A list of `data.frame`s containing coordinates for the total outline for each axis
#' @slot metadata A list of metadata generated by `drawSegmentation()`
#' @slot structure_tables A list of tables with structure per slice per plane generated by `drawSegmentation()`

setClass("segmentation", representation(
  slices = "list",
  ontology = "data.frame",
  outlines = "list",
  metadata = "list",
  structure_tables = "list",
  assays = "list",
  projections = "list"
))

#' S4 class representing a segmentation point set
#'
#' Holds all the data necessary to build a set of polygons via `buildPolygon` in order to be plotted.
#'
#' @slot coords A `data.frame` containing ordered `x` and `y` coordinates for polygon drawing
#' @slot slice A `character` containing the slice number
#' @slot structure A `character` containing the structure ID
#' @slot id A `character` containing the polygon ID (group level aesthetic for plotting)
#' @slot subid A `character` containing the polygon sub-ID (subgroup level aesthetic for plotting)

setClass("segPointSet", representation(
  coords = "data.frame",
  slice = "character",
  structure = "character",
  id = "character",
  subid = "character"
))

#' S4 class representing an assay associated with a segmentation
#'
#' Holds numerical values for features in samples, and provides a one-to-many mapping for every sample to one or more structures
#'
#' @slot values A `matrix` containing features (rows) in each sample (columns)
#' @slot mapping A `list` in which each sample (list item name) contains the segmentation structural IDs to which samples are mapped
#' @slot sampledata A `data.frame` containing other information on samples (e.g. description, sample metadata)

setClass("segmentationAssay", representation(
  values = "matrix",
  mapping = "list",
  sampledata = "data.frame"
))

setGeneric("metaData", function(x) {
  standardGeneric("metaData")
})

setMethod("metaData", c(x = "segmentation"), function(x) {
  return(x@metadata)
})

setGeneric("ontology", function(x) {
  standardGeneric("ontology")
})

setMethod("ontology", c(x = "segmentation"), function(x) {
  return(x@ontology)
})


setGeneric("assays", function(x) {
  standardGeneric("assays")
})

setMethod("assays", c(x = "segmentation"), function(x) {
  return(x@assays)
})

setMethod("show", "segmentation", function(object) {
  if(metaData(object)$units == "Unknown") units <- "Unknown" else units <- c("Unknown", "m", "mm", "micron")[metaData(object)$units + 1]
  cat("      Segmentation from file: ", metaData(object)$filename, "\n")
  cat("                    Plane(s): ", paste(metaData(object)$planes, collapse = ", "), "\n")
  cat("                  Directions: ", paste(metaData(object)$dirs, collapse = " to "), "\n")
  cat("       Dimensions (original): ", paste(metaData(object)$dims_original, collapse = " x "), "\n")
  cat("      Dimensions (effective): ", paste(metaData(object)$dims_effective, collapse = " x "), "\n")
  cat("            Pixel dimensions: ", paste(metaData(object)$pixdim, collapse = " x "), "\n")
  cat("             Dimension units: ", units, "\n")
  cat("             Reference space: ", metaData(object)$reference_space, "\n")
  cat("              Structures (n): ", length(metaData(object)$structures), "\n")
  cat("             Structures (ID): ", paste(head(metaData(object)$structures), collapse = ", "), "and", (length(metaData(object)$structures) - length(head(metaData(object)$structures))), "more. \n")
  cat("       Structures (acronyms): ", paste(head(ontology(object)[as.character(metaData(object)$structures), "acronym"]), collapse = ", "), "and", (length(ontology(object)[metaData(object)$structures, "acronym"]) - length(head(ontology(object)[metaData(object)$structures, "acronym"]))), "more. \n")
  cat("Type showCitation(\"name_of_segmentation\") to display the citation(s) for this segmentation.", sep = "")
  })

setGeneric("showCitation", function(x) {
  standardGeneric("showCitation")
})

setMethod("showCitation", "segmentation", function(x) {
  for(n in names(x@metadata$citation)) {
    cat("Citation (", n, "):\n", sep = "")
    print(x@metadata$citation[[n]])
    }
})
